import "./globals.css";
import Home from "../pages/index";


export const metadata = {
  title: "Dev To",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body>{<Home/>}</body>
    </html>
  );
}
