import { Inter } from "next/font/google";
import "./globals.css";
import Home from "../pages/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dev To",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>{<Home/>}</body>
    </html>
  );
}
